name: neuro_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu121
      - --extra-index-url https://pypi.org/simple
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torchaudio==2.5.1+cu121
      - onnxruntime-gpu
      - transformers
      - bitsandbytes
      - accelerate
      - fpdf2
      - streamlit
      - pytest
      - black
      - ruff
