"""
Centralized localization utility for NeuroGemma.
Supports English (en) and Spanish (es).
"""

from typing import Any

LOCALIZATION_DATA: dict[str, dict[str, str]] = {
    "English": {
        "page_title": "NeuroGemma | AI-Powered Radiology Assistant",
        "app_subtitle": "Advanced MRI Analysis & Clinical Decision Support",
        "control_center": "Control Center",
        "mock_mode": "Mock Mode",
        "mock_mode_help": "Simulate AI model outputs without local GPU inference. Ideal for demonstrations and testing UI logic.",
        "select_scenario": "Select Clinical Scenario",
        "select_scenario_help": "Choose a pre-defined radiology scenario to simulate pipeline behavior.",
        "load_mock_data": "Load Mock Data",
        "clear_session": "Clear Session",
        "clear_session_help": "Wipe all results, logs, and clinical image data from the current session.",
        "system_status_ready": "System Status: Ready",
        "tab_diagnostic": "Diagnostic View",
        "tab_logs": "Technical Logs",
        "welcome_message": "Welcome to NeuroGemma. Please upload a brain scan to begin analysis.",
        "uploader_label": "Drag and drop or click to upload MRI Scan",
        "uploader_help": "Supported formats: JPG, PNG • Max size: 20MB",
        "validating_scan": "Validating Scan...",
        "scan_validated": "Scan Validated",
        "upload_error": "Upload Error",
        "redirecting": "Redirecting to analysis dashboard...",
        "change_image": "Change Image",
        "run_pipeline": "Run Pipeline",
        "orchestrating_models": "Orchestrating Models...",
        "analysis_complete": "Analysis Complete!",
        "pipeline_error": "Pipeline Error",
        "quantitative_analysis": "#### Quantitative Analysis",
        "clinical_narrative": "#### Clinical Narrative",
        "vlm_analyzing": "MedGemma VLM is analyzing the scan...",
        "vlm_error": "VLM Synthesis Error. Check logs for details.",
        "vlm_triggered": "VLM Triggered: Narrative Generated",
        "vlm_skipped": "VLM Skipped",
        "waiting_logic": "Waiting for logic gate decision...",
        "generate_report": "Generate Radiology Note",
        "generate_report_help": "Download the professional radiology report as a PDF.",
        "technical_journal": "### Technical Decision Journal",
        "no_activity": "No activity recorded yet.",
        "start_pipeline_hint": "Start the inference pipeline to generate a technical audit trail.",
        "technical_metadata": "Technical Metadata",
        "language_label": "Language / Idioma",
        "plane": "Plane",
        "sequence": "Sequence",
        "depth": "Depth",
        "axial_flair": "Axial-FLAIR",
        "sagittal_t1": "Sagittal-T1",
        "vlm_skipped_reason": "Analysis Skipped (Scan not Axial-FLAIR)",
        "report_header": "NeuroGemma Clinical",
        "report_subheader": "Professional Radiology Note",
        "report_footer": "CONFIDENTIAL - FOR CLINICAL USE ONLY",
        "report_summary": "1. Clinical Summary",
        "report_date": "Date:",
        "report_filename": "Original Filename:",
        "report_cnn": "2. Automated Classifications (CNN)",
        "report_plane": "Anatomical Plane:",
        "report_sequence": "Pulse Sequence:",
        "report_depth": "Slice Depth:",
        "report_vlm": "3. Clinical Findings (VLM Narrative)",
        "report_no_narrative": "No narrative findings generated.",
        "report_disclaimer_title": "CRITICAL DISCLAIMER:",
        "report_disclaimer_body": "AI-generated draft for clinical review. Not a final diagnosis. This report must be reviewed and validated by a licensed radiologist before clinical implementation.",
        "report_validated_by": "Validated by:",
        "report_validation_date": "Date of Validation:",
        "ready_inference": "Ready for inference. Click 'Run Pipeline' to start.",
        "stage_id": "IDENTIFICATION",
        "stage_gate": "LOGIC GATE",
        "stage_synthesis": "SYNTHESIS",
        "stage_complete": "COMPLETE",
        "browse_files": "Browse files",
        "drag_drop": "Drag and drop file here",
        "limit_info": "Limit 20MB per file",
        "meta_filename": "filename",
        "meta_format": "format",
        "meta_size": "size",
        "meta_width": "width",
        "meta_height": "height",
        "meta_timestamp": "timestamp",
        "report_page_label": "Page",
        "ui_fullscreen": "Fullscreen",
        "log_UPLOAD_SUCCESS": "UPLOAD_SUCCESS",
        "log_PLANE_CLASSIFIED": "PLANE_CLASSIFIED",
        "log_SEQUENCE_CLASSIFIED": "SEQUENCE_CLASSIFIED",
        "log_DEPTH_ESTIMATED": "DEPTH_ESTIMATED",
        "log_GATE_DECISION": "GATE_DECISION",
        "log_NARRATIVE_GENERATED": "NARRATIVE_GENERATED",
        "log_SYNTHESIS_SKIPPED": "SYNTHESIS_SKIPPED",
        "log_ERROR": "ERROR",
        "out_IMAGE_VALIDATED": "IMAGE_VALIDATED",
        "out_TRIGGERED": "TRIGGERED",
        "out_SKIPPED": "SKIPPED",
        "out_SUCCESS": "SUCCESS",
        "out_FAILURE": "FAILURE",
        "out_DISABLED": "DISABLED",
        "meta_plane": "plane",
        "meta_sequence": "sequence",
        "val_axial": "axial",
        "val_sagittal": "sagittal",
        "val_coronal": "coronal",
        "val_flair": "flair",
        "val_t1": "t1",
        "val_t2": "t2",
        "val_t1-w": "t1-w",
        "val_t1-ce": "t1-ce",
        "val_t2-w": "t2-w",
        "val_others": "others",
        "val_non_brain_mri": "non_brain_mri",
        "sagittal_depth_help": "The range for sagittal images is limited between 0 (central image) and 1 (extreme images) due to symmetry between hemispheres."
    },
    "Español": {
        "page_title": "NeuroGemma | Asistente de Radiología cerebral con IA",
        "app_subtitle": "Análisis Avanzado de RM y Soporte de Decisiones Clínicas",
        "control_center": "Centro de Control",
        "mock_mode": "Modo Simulación",
        "mock_mode_help": "Simular salidas de modelos de IA sin inferencia local por GPU. Ideal para demostraciones y pruebas de lógica de interfaz.",
        "select_scenario": "Seleccionar Escenario Clínico",
        "select_scenario_help": "Elegir un escenario de radiología predefinido para simular el comportamiento del pipeline.",
        "load_mock_data": "Cargar Datos de Simulación",
        "clear_session": "Reiniciar Sesión",
        "clear_session_help": "Borrar todos los resultados, registros y datos de imágenes clínicas de la sesión actual.",
        "system_status_ready": "Estado del Sistema: Listo",
        "tab_diagnostic": "Vista Diagnóstica",
        "tab_logs": "Logs Técnicos",
        "welcome_message": "Bienvenido a NeuroGemma. Por favor, suba un escaneo cerebral para comenzar el análisis.",
        "uploader_label": "Arrastre y suelte o haga clic para subir un escaneo de RM",
        "uploader_help": "Formatos soportados: JPG, PNG • Tamaño máx: 20MB",
        "validating_scan": "Validando Imagen...",
        "scan_validated": "Imagen Validada",
        "upload_error": "Error de Carga",
        "redirecting": "Redirigiendo al tablero de análisis...",
        "change_image": "Cambiar Imagen",
        "run_pipeline": "Analizar Imagen",
        "orchestrating_models": "Generando respuesta de los modelos...",
        "analysis_complete": "¡Análisis Completado!",
        "pipeline_error": "Error de procesamiento",
        "quantitative_analysis": "#### Análisis Cuantitativo",
        "clinical_narrative": "#### Narrativa Clínica",
        "vlm_analyzing": "MedGemma VLM está analizando la imagen...",
        "vlm_error": "Error de Síntesis VLM. Consulte los registros para más detalles.",
        "vlm_triggered": "VLM Activado: Narrativa Generada",
        "vlm_skipped": "VLM Omitido",
        "waiting_logic": "Esperando decisión del filtro de decisión...",
        "generate_report": "Generar Nota Radiológica",
        "generate_report_help": "Descargar el informe radiológico profesional en formato PDF.",
        "technical_journal": "### Diario de Decisiones Técnicas",
        "no_activity": "Aún no se ha registrado actividad.",
        "start_pipeline_hint": "Inicie el pipeline de inferencia para generar un rastro de auditoría técnica.",
        "technical_metadata": "Metadatos Técnicos",
        "language_label": "Language / Idioma",
        "plane": "Plano",
        "sequence": "Secuencia",
        "depth": "Profundidad",
        "axial_flair": "Axial-FLAIR",
        "sagittal_t1": "Sagittal-T1",
        "vlm_skipped_reason": "Análisis Omitido (La imagen no es Axial-FLAIR)",
        "report_header": "NeuroGemma Clínico",
        "report_subheader": "Nota Radiológica Profesional",
        "report_footer": "CONFIDENCIAL - SOLO PARA USO CLÍNICO",
        "report_summary": "1. Resumen Clínico",
        "report_date": "Fecha:",
        "report_filename": "Nombre de Archivo Original:",
        "report_cnn": "2. Clasificaciones Automatizadas (CNN)",
        "report_plane": "Plano Anatómico:",
        "report_sequence": "Secuencia de Pulsos:",
        "report_depth": "Profundidad de Corte:",
        "report_vlm": "3. Hallazgos Clínicos (Narrativa VLM)",
        "report_no_narrative": "No se generaron hallazgos narrativos.",
        "report_disclaimer_title": "AVISO CRÍTICO:",
        "report_disclaimer_body": "Borrador generado por IA para revisión clínica. No es un diagnóstico final. Este informe debe ser revisado y validado por un experto clínico antes de su implementación clínica.",
        "report_validated_by": "Validado por:",
        "report_validation_date": "Fecha de Validación:",
        "ready_inference": "Listo para la inferencia. Haga clic en 'Analizar Imagen' para comenzar.",
        "stage_id": "IDENTIFICACIÓN",
        "stage_gate": "FILTRO DE DECISIÓN ",
        "stage_synthesis": "SÍNTESIS",
        "stage_complete": "COMPLETADO",
        "browse_files": "Seleccionar archivo",
        "drag_drop": "Arrastra y suelta el archivo aquí",
        "limit_info": "Límite de 20MB por archivo",
        "meta_filename": "nombre_archivo",
        "meta_format": "formato",
        "meta_size": "dimensiones",
        "meta_width": "ancho",
        "meta_height": "largo",
        "meta_timestamp": "fecha_subida",
        "report_page_label": "Página",
        "ui_fullscreen": "Ampliar",
        "log_UPLOAD_SUCCESS": "CARGA_EXITOSA",
        "log_PLANE_CLASSIFIED": "PLANO_CLASIFICADO",
        "log_SEQUENCE_CLASSIFIED": "SECUENCIA_CLASIFICADA",
        "log_DEPTH_ESTIMATED": "PROFUNDIDAD_ESTIMADA",
        "log_GATE_DECISION": "DECISION_FILTRO",
        "log_NARRATIVE_GENERATED": "NARRATIVA_GENERADA",
        "log_SYNTHESIS_SKIPPED": "SINTESIS_OMITIDA",
        "log_ERROR": "ERROR_TECNICO",
        "out_IMAGE_VALIDATED": "IMAGEN_VALIDADA",
        "out_TRIGGERED": "ACTIVADO",
        "out_SKIPPED": "OMITIDO",
        "out_SUCCESS": "EXITO",
        "out_FAILURE": "FALLO",
        "out_DISABLED": "DESACTIVADO",
        "meta_plane": "plano",
        "meta_sequence": "secuencia",
        "meta_raw_scores": "probabilidades",
        "meta_depth": "profundidad",
        "val_axial": "axial",
        "val_sagittal": "sagital",
        "val_coronal": "coronal",
        "val_non_brain_mri": "no_cerebral",
        "val_flair": "flair",
        "val_t1": "t1",
        "val_t2": "t2",
        "val_t1-w": "t1-w",
        "val_t1-ce": "t1-ce",
        "val_t2-w": "t2-w",
        "val_others": "otros",
        "sagittal_depth_help": "El rango para imágenes sagitales está limitada entre 0 (imagen central) y 1 (imágenes extremos) debido a la simetría entre hemisferios"
    }
}

def get_text(key: str, lang: str) -> str:
    """
    Retrieve translated text for a given key and language.
    
    Args:
        key: The localization key.
        lang: The language to use ('English' or 'Español').
        
    Returns:
        The translated string, or the key itself if not found.
    """
    return LOCALIZATION_DATA.get(lang, LOCALIZATION_DATA["English"]).get(key, key)
