[theme]
primaryColor = "#007BFF"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#E9ECEF"
textColor = "#2C3E50"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
